<?php

namespace AppBundle\Repository;

/**
 * ProductsListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsListRepository extends \Doctrine\ORM\EntityRepository
{
}
