app:
    type: annotation
    resource: '@AppBundle/Controller/DefaultController.php'

app_api:
    type: rest
    prefix: /
    resource: '@AppBundle/Resources/config/routing.yml'

api_login_check:
    path: /api/login_check

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /docs
